# Generated by Django 5.0 on 2024-01-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0002_indices'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indices',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indices',
            name='ponderacion',
            field=models.FloatField(blank=True, help_text='Valoration for the index', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='indices',
            unique_together={('categoria', 'descripcion', 'ponderacion')},
        ),
    ]
