# Generated by Django 5.0 on 2024-01-22 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0003_alter_indices_unique_together_indices_ponderacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='indices',
            name='descripcion',
            field=models.CharField(help_text='Descripcion de el indice ', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripcion de el tipo de ajuste', max_length=100, unique=True)),
                ('ajuste', models.FloatField(help_text='Ponderacion de ajuste', max_length=3)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Indices',
                'unique_together': {('descripcion', 'ajuste')},
            },
        ),
    ]
