# Generated by Django 5.0 on 2024-01-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0004_alter_indices_descripcion_ajustes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajustes',
            options={'verbose_name_plural': 'Ajustes'},
        ),
    ]
