# Generated by Django 5.0 on 2024-01-22 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0005_alter_ajustes_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ajustes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ajustes',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ind.categoria'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ajustes',
            unique_together={('categoria', 'descripcion', 'ajuste')},
        ),
    ]
